# Generated by Django 4.2.7 on 2023-12-05 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLASS',
            fields=[
                ('class_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=4)),
                ('building_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=4)),
                ('building_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Principal', 'Principal'), ('Vice Principal', 'Vice Principal')], max_length=100)),
                ('joining_date', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('room_number', models.CharField(max_length=4)),
                ('building_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('dept_designation', models.CharField(choices=[('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Member', 'Member')], max_length=100)),
                ('joining_date', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=100)),
                ('dept_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=500)),
                ('is_captain', models.BooleanField(default=False)),
                ('CLASS', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.class')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
