# Generated by Django 4.2.7 on 2023-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principal',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
