# Generated by Django 4.2.7 on 2023-12-13 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_alter_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CLASS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')]),
        ),
    ]
