# Generated by Django 4.2.7 on 2023-12-13 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_alter_student_class_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^[0-9]*$')]),
        ),
    ]
